### ISSUE TITLE
add paragraph of how to use the doc

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#10]
We might add a paragraph on top of each API which describes how to use the api doc. It is obviously not self-explanatory:

> Thanks! I was not familiar with the navigation structure of the page, It did not result obvious to me.

**Comment by karussell** [comment]
We could somehow highlight the nodes as clickable?

Still I would find it better if the ReDoc search does what it should do - currently it is broken :/

**Comment by oblonski** [comment]
This https://github.com/graphhopper/directions-api-doc/commit/e4cdbe431a1c4c15dae607a8a44f3ce8bf0f8b49 displays expanded responses

**Comment by oblonski** [comment]
Need to revert this.

**Comment by oblonski** [comment]
200 response are collapsed by default now.

**Comment by oblonski** [comment]
No idea yet how to make collapsable objects bold. There seems to be ways to overwrite default CSS, I just dont know how yet.

**Comment by karussell** [comment]
I can have a look into it. Would "underlining" them being more intuitive?

**Comment by oblonski** [comment]
or just bold, if we find out how it works we can just try it both.

**Comment by karussell** [comment]
The "200" is already bold. I'm currently fiddling with CSS to make this happen but is hard due to the autogenerated IDs that come without a meaningful name.
