### ISSUE TITLE
Problems with finding specific key and values

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-doc#13]
Copied from https://github.com/graphhopper/directions-api-doc/issues/5#issuecomment-476851015

Interestingly it is hard to find the reason description (and other stuff) in the docs.

If I search via the web browser (inside the page) => does not find it
If I search via the search input => does not find it

Just going the lengthy way from "Route Optimization API"
 -> "retrieve solution"
 -> 200
 -> solution
 -> unassigned
 -> details

gives what I want. But I can't even link into this. This is a bit ugly.

There should be an option to "expand all nodes" or the search should do a better work and should be based on the raw data. See https://github.com/Rebilly/ReDoc/issues/562 and my own issue (haha!) https://github.com/Rebilly/ReDoc/issues/63

Workaround 1: go to https://docs.graphhopper.com/openapi.json and use the web browser search

Workaround 2: implement a button that expands all the entries like explained here: https://github.com/Rebilly/ReDoc/issues/593

**Comment by karussell** [comment]
Hmmh, this is getting ugly.

Even simple links do not always work like: https://docs.graphhopper.com/#operation/solveVRP

gives this result:

![image](https://user-images.githubusercontent.com/129644/56519424-4f0cda00-6542-11e9-9cab-485deb2ce858.png)

**Comment by oblonski** [comment]
This is indeed ugly. I cannot reproduce it on Google Chrome, but on Firefox.

**Comment by karussell** [comment]
Thx - have reported it here: https://github.com/Rebilly/ReDoc/issues/896

**Comment by oblonski** [comment]
Thanks. I am just figuring out how to update the version of Redoc to the latest one (it might be fixed there?) ... It seems that we need to create a new repo from scratch, thus, need to overwrite everything in our repo??? This would be ugly too.

**Comment by karussell** [comment]
Will the following work?

 * create a new (temporary) repo with new files
 * remove all files (except the spec and readme) from this repo
 * copy the new files from the temporary repo into this repo (except spec and readme)

**Comment by karussell** [comment]
This is now fixed via #33!
