### ISSUE TITLE
evaluate open-api-generator for generating our clients

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#14]
https://openapi-generator.tech/docs/generators/java

**Comment by karussell** [comment]
I'll try to use https://github.com/OpenAPITools/openapi-generator and adapt our clients here: https://github.com/graphhopper/directions-api-clients

**Comment by karussell** [comment]
The remaining problem is `minItems` for Vehicle. Can we remove this? Or move this to `vehicles`?

**Comment by karussell** [comment]
Moved it to vehicles: https://github.com/graphhopper/directions-api-doc/blob/master/spec/openapi.yaml#L2120

**Comment by karussell** [comment]
I have tried now swagger codegen again (3.0.11) and I'm making progress. Have also our java-examples running (mainly).

One problem the code generator stumbles over is our pickup definition. Can we remove the description?

```
"pickup": {
    "allOf": [
    {
        "$ref": "#/components/schemas/Stop"
    },
    {
        "description": "This is a pickup."
    }
    ]
},
"delivery": {
    "$ref": "#/components/schemas/Stop"
},
```

**Comment by karussell** [comment]
No, even if I make pickup simpler I still get this strange serialization:

```
"pickup":{...,"":"Stop"}
```
