### ISSUE TITLE
the license of our docs should be from us

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-doc#20]
Should we change the Author of our documentation in the MIT license?

https://github.com/graphhopper/directions-api-doc/blob/master/LICENSE

Or even move to Apache license?

**Comment by oblonski** [comment]
Oh yes, we should change the license.

**Comment by karussell** [comment]
to Apache?

**Comment by oblonski** [comment]
Ja, oder?

**Comment by karussell** [comment]
Ok, just copied it from graphhopper/graphhopper :)

**Comment by oblonski** [comment]
👍
