### ISSUE TITLE
the default of points_encoded seems to be true

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#21]
not `false` as the doc suggests. @karussell Is that correct?

**Comment by karussell** [comment]
Yes, unfortunately it is true.

**Comment by oblonski** [comment]
Ok. Then I change the `default` value.

**Comment by karussell** [comment]
Thanks :+1: 

Really interesting that the docs are so tightly coupled with the spec and we improve and clarify those things :)

**Comment by oblonski** [comment]
Yes. I completely changed the way I work with our APIs, i.e. I use our docs much more often than before and along with the docs I use Insomnia or Postman to convince myself whether the docs tell the truth or not.
