### ISSUE TITLE
improve search

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#31]
@thisismo wrote:

> Jetzt wäre es super wenn man beim draufklicken direkt zu dem Text springen könnte wo das Wort vorkommt, über einen festen Link zu einem bestimmten Abschnitt (z.B. bestimmter Parameter von GET) weitergeleitet werden kann.

Jo, das sollte machbar sein.

> Am Besten schreibst Du kurz selbst welche Sachen Du gemacht hast.

Bisher wurden nur die Gruppen- und Operationmodels zu dem Suchindex hinzugefügt. Ich habe das so abgeändert, dass es eben auch jedes einzelne Field (Also jede Key-Value Kombination) in den nested Operationmodels hinzufügt.
Und ich habe noch einen kleinen Workaround für den Firefox Bug (https://github.com/Redocly/redoc/issues/896) gefunden. Dieser ist jedoch in dem Script, welches Redoc initialisiert, zu implementieren.

**Comment by oblonski** [comment]
@thisismo wrote:

Hey, ich habe gestern das Springen zu den einzelnen Feldern fertiggestellt.
Ausprobieren kann man das ganze einfach wieder durch clonen und lokalem ausführen der standalone Branch (https://github.com/graphhopper/directions-api-doc/tree/standalone).
Der Link zu meinem Redoc Fork ist https://github.com/thisismo/redoc/tree/extended-search

**Comment by oblonski** [comment]
@thisismo This is really cool. Now the search is useful.
Does this requires that all nested objects need to be unfolded by default? I find it a bit confusing and I think it is better if the user can unfold it.

**Comment by thisismo** [comment]
No, it doesn't. However, this leads to a bug which I'm about to fix right now.

**Comment by thisismo** [comment]
The bug fixed standalone is now available at https://github.com/graphhopper/directions-api-doc/tree/standalone.
Feel free to try :-)

**Comment by karussell** [comment]
Oh, my - this is really great and works perfectly :+1:

**Comment by karussell** [comment]
@oblonski can we merge this with master and see if it works also on docs.graphhopper?

**Comment by oblonski** [comment]
@karussell I assume that we need to change the way it is deployed. As far as I can see, index.html in the standalone branch is ready to use whereas in our current approach, travis tests openapi.yml and builds index.html.

**Comment by oblonski** [comment]
Travis does npm run build && npm run gh-pages. Latter deploys the doc to github pages. I assume that this is not possible anymore.

**Comment by karussell** [comment]
@thisismo what needs to be updated when there is a change in openapi.yml e.g. new field or added description? Can you have a look into the current deployment process and see if this is possible for your branch too?

**Comment by thisismo** [comment]
Actually nothing has to be updated. The script fetches the openapi.json each time by URL.

**Comment by karussell** [comment]
Great! Do you know why we have to call npm in the master branch?

**Comment by thisismo** [comment]
The master branch uses swagger to visualize live changes made to the openapi.yaml
I don't know if that's still necessary tho.

**Comment by karussell** [comment]
I don't this this is important. Or do you need it @oblonski?

**Comment by oblonski** [comment]
No, I do not need it for live changes. Travis uses it also to test the openapi spec against the openapi schema. If this is successful, it build the index.html and put it to a folder called web_deploy which is then used to deploy the doc to gh pages. If we do not need this deployment cycle, we can omit it and use index.html directly.

**Comment by karussell** [comment]
The check would be still useful, so we would need the swagger-repo. 

Additionally the result is deployed into the gh-pages branch. Either we keep this and e.g. copy the index.html or we serve the github page directly from master. @thisismo can you investigate the best option?

**Comment by thisismo** [comment]
Sure, I'm on it!

**Comment by thisismo** [comment]
Ok, apparently you can specify 'redocURL' in 'redoc-config.yaml'.
This way, we can just paste our 'redoc.standalone.js' into the '/web' folder, adjust the config to use it and use the old building procedure.

**Comment by karussell** [comment]
Would you post the required changes as PR or is this already done in the branch?

**Comment by karussell** [comment]
Ups, was already done. Ugly github that does not update its site in the background ...

**Comment by karussell** [comment]
Fixed via #33 

This is so great! Thx a bunch!!
