### ISSUE TITLE
Minor issue when linking to parameter

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-doc#34]
The new search is really great and makes everything more pleasant.

It also creates a link to parameters e.g.

https://docs.graphhopper.com/#operation/getRoute/parameters/pass_through

When I click on the item in the search this works but when I open the URL in a new window it just goes to the Routing API and not further.

**Comment by thisismo** [comment]
Appears to be the Firefox Bug again, as it works fine for me on chrome.
I thought I fixed it within the Redoc Project, but I doesn't seem like it.
Anyways, I'm working on it.

**Comment by karussell** [comment]
>  I thought I fixed it within the Redoc Project, but I doesn't seem like it.

Do you mean that you wanted to fix it with the open PR upstream first?

**Comment by thisismo** [comment]
Fixed in latest standalone. See https://github.com/graphhopper/directions-api-doc/pull/36
