### ISSUE TITLE
Cannot link to collapsed symmetrical matrix parameter

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-doc#35]
slightly different to #34 IMO

![image](https://user-images.githubusercontent.com/129644/63041856-11550800-bec9-11e9-8da1-a48599ea87be.png)

If you search for snap_prevention you can click on the first two entries and it will correctly forward you, but the other two are hidden and no action is taken I think. Only if you click on the button "SymmetricalMatrixRequest" it will work.

https://docs.graphhopper.com/#operation/postMatrix/body/snap_preventions

**Comment by thisismo** [comment]
Also fixed in latest standalone! :-) See https://github.com/graphhopper/directions-api-doc/pull/36

**Comment by karussell** [comment]
This does not seem to work in firefox (#34 is now fixed :))

**Comment by thisismo** [comment]
Are you using the link from above? The bug fix included a change in IDs, so the new link is https://docs.graphhopper.com/#operation/postMatrix/body/json/SymmetricalMatrixRequest/snap_preventions

**Comment by karussell** [comment]
Ah, thanks!
