### ISSUE TITLE
output of the MapMatching is encoded using polyline encoding

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#39]
> Perhaps this is obvious for the experienced (in terms of working with OSM data) users, but it was not obvious for me. Please state in the swagger docs that the output of the MapMatching is encoded using polyline encoding.

**Comment by karussell** [comment]
This is probably lost when we migrated to the new docs: the response (and also many parameters like points_encoded=true|false) is currently identical to the Routing API.
