### ISSUE TITLE
priority feature needs to be refined

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#40]

**Comment by karussell** [comment]
What about instead of

> Specifies the priority. Can be 1 = high priority to 10 = low priority. Often there are more services/shipments than the available vehicle fleet can handle. Then you could assign priorities to differentiate high priority tasks from those that can be served later or omitted at all.

we write something like:

> Specifies the priority. Can be 1 = high priority to 10 = low priority. Often there are more services/shipments than the available vehicle fleet can handle. Then you can set priorities to differentiate high priority tasks from those that could be left unassigned. I.e. the lower the priority the earlier these tasks are omitted in the solution.

**Comment by oblonski** [comment]
👍
