### ISSUE TITLE
Graphhopper Logo yields 404

### ISSUE THREAD

**Issue by easbar** [graphhopper/directions-api-doc#43]
I am getting 404 for https://graphhopper.com/img/header.png and the logo is not shown here:
https://graphhopper.com/api/1/examples/

![image](https://user-images.githubusercontent.com/17603532/67745524-c5742280-fa24-11e9-8472-6850320591a5.png)

**Comment by karussell** [comment]
Uh, thanks! Have fixed it: https://github.com/graphhopper/directions-api-js-client/commit/cc6c800b530d7b31c47e1563487ffce2e4a9540e
