### ISSUE TITLE
add description for unassigned reason code

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#5]

**Comment by karussell** [comment]
Interestingly it is very hard to find the reason description in the docs.

If I search via the web browser => does not find it
If I search via the search input => does not find it

Just going the lengthy way from "retrieve solution" -> solution -> unassigned -> details gives what I want. But I can't even link into this. This is a bit ugly.

**Comment by oblonski** [comment]
>See Rebilly/ReDoc#562 and my own issue (haha!) Rebilly/ReDoc#63
 
😆
