### ISSUE TITLE
Where can I specify the output of the POST route request?

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#51]
The GET request allows me to specify, for example, whether I want instructions or not or points encoded etc.. Is this not possible with the POST request? If it is, it is not documented.

**Comment by oblonski** [comment]
If it is not, we need to refine the response doc from this POST endpoint.

**Comment by karussell** [comment]
Everything is possible with the POST request too, yes. 

> Is this not possible with the POST request? If it is, it is not documented.

:+1: 

Currently we are a bit lazy and link to the GET request:

> For the remaining parameters please refer to the GET request guide.

**Comment by oblonski** [comment]
Ah ok. Makes sense.

> To do a request you send JSON data and the only URL parameter will be the key

Then this is wrong - I guess.

**Comment by oblonski** [comment]
I will adjust it.

**Comment by karussell** [comment]
> > To do a request you send JSON data and the only URL parameter will be the key

> Then this is wrong - I guess.

What do you mean? The only URL parameter is the key. All other parameters have to go into the JSON.

**Comment by oblonski** [comment]
Oh no. This is really confusing.

**Comment by karussell** [comment]
What is confusing?

**Comment by karussell** [comment]
It is relative simple IMO: 

GET request => parameters go into URL
POST request => parameter go into JSON

And the URL always contains the domain + endpoint + API key

**Comment by oblonski** [comment]
> What is confusing?

That the Request Body schema only consist of `points`, `snap_preventions`, `point_hints` and `vehicle`.

**Comment by karussell** [comment]
Yes, the request body also has other options and I agree that listing only these plural keys is very confusing.
