### ISSUE TITLE
Add all query parameters from GET to request body of POST

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-doc#53]

**Comment by oblonski** [comment]
How do we want to handle this

`round_trip.distance`

and related fields?

Should `round_trip` be an object and distance, seed, etc. its fields?

**Comment by oblonski** [comment]
I assume that `distance` is currently a root field which is not as intuitive as the object model.

**Comment by oblonski** [comment]
Probably it will just be handled as `ch.disabled`

**Comment by karussell** [comment]
> Probably it will just be handled as ch.disabled

Yes, exactly.

**Comment by karussell** [comment]
Thanks for this!
