### ISSUE TITLE
scrolling documentation with chrome/chromium is not possible

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-doc#60]
Only reproducible with chrome/chromium: When you scroll down a bit, the site will jump immediately to the top.

The same issue happens if you

 1. Click on "Authentication" in the left menu and then
 2. Click on the chain/link icon near the next "Route Optimization API" header (left of it)
 3. site will immediately scroll to the top

**Comment by karussell** [comment]
As a temporary workaround you can open our documentation via https://editor.swagger.io/?url=https://docs.graphhopper.com/openapi.json

**Comment by karussell** [comment]
It seems to be there are many issues with redoc and chrome >=80: Redocly/redoc#1202

So we switched temporarily to the bug-fixed official version (where search is suboptimal) https://github.com/graphhopper/directions-api-doc/commit/660f78ca4413b95b409a654f50b739b719561b2c

**Comment by oblonski** [comment]
It seems that the search function no longer works at all.

**Comment by karussell** [comment]
Yes. But everything was completely broken for chrome users and so we had to act fast. @thisismo then upgraded to the most recent version where these problems are fixed. Unfortunately the search and linking that we all loved is gone and has to be reintegrated now.

That was the reason I really wanted to have these two features in the main repo to avoid work when new versions arrive, but the authors did not even had a look into our contribution I fear: https://github.com/Redocly/redoc/pull/1067

**Comment by oblonski** [comment]
Thanks @karussell. Maybe we should also look for an alternative doc generator. I will take a look.

**Comment by karussell** [comment]
Yeah, there are many such tools out there and ReDoc seems to be often recommended. I just put together a list of active projects:

## Open Source

 * https://github.com/slatedocs/slate
 * https://github.com/mermade/widdershins
 * https://github.com/opticdev/optic
 * https://github.com/apidoc/apidoc 
 * https://github.com/tmcw/docbox (e.g. mapbox and mapillary uses this)
 * https://github.com/ouropencode/OpenDocumenter
 * https://github.com/Wiredcraft/carte
 * https://github.com/Mermade/openapi-gui
 * https://github.com/Nexmo/nexmo-oas-renderer
 * https://github.com/isa-group/oas-tools

(some of them I picked via https://openapi.tools/#documentation)
 
## Commercial

 * https://stoplight.io/api-documentation/ (also free hosting possible via: https://api-docs.io/ but e.g. no custom domain)
 * https://blog.readme.com/how-to-use-openapi-and-swagger-spec-for-documentation/
 * https://www.postman.com/
 * https://bump.sh/
 * https://www.apitree.com
 * https://konghq.com/

**Comment by karussell** [comment]
Stoplight just released 2.0 https://stoplight.io/blog/stoplight-v2-0-0-release/

**Comment by karussell** [comment]
The new Hetzner docs look good: https://docs.hetzner.com/ ... they seem to be using a [Gatsby JS framework](https://www.gatsbyjs.com/) (unfortunately there is no OpenAPI 3.0 converter)
